services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongodb
  web-application:
    build: ./
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_URLS=http://localhost
      - ASPNETCORE_HTTP_PORT=5000
    container_name: web-app-back
  front:
    build: ./ClientApp/client-app/
    ports:
      - 4200:80
    container_name: angular-app-front
